kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: toolchaincluster-member-toolchain-member-operator-toolchaincluster
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create