name: ci-build
on:
  push:
    branches:
      - master
    tags-ignore:
      - '*.*'
  pull_request:
    branches:
      - master

jobs:
  test-with-coverage:
    name: Test with Coverage
    runs-on: ubuntu-20.04
    steps:
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19.x
    
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Test
      run: |
        make test-with-coverage
    - name: Upload code coverage
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./out/coverage/coverage.txt
        flags: unittests # optional
        fail_ci_if_error: true # optional (default = false)
        verbose: true # optional (default = false)
    
  golangci:
    name: GolangCI Lint
    runs-on: ubuntu-20.04
    steps:
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19.x
        
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.52.0
        skip-pkg-cache: true
        skip-build-cache: true
        args: --config=./.golangci.yml --verbose
